main: com.falsegamer.AdvancedDIYSpy.DIYspyMain
name: AdvancedDIYspy
version: 1.2
author: TheFalsegamer4

commands:
  commandspy:
    aliases: [cmdspy, cspy]
    usage: /cspy
    description: Toggles Command Spy (Can also do /cspy)
  socialspy:
    aliases: [sspy]
    usage: /sspy
    description: Toggles Social Spy (Can also do /sspy)
  spyreload:
    usage: /spyreload
    description: Reloads the config file
